#!/bin/sh
# Exit when error happens
set -e

echo "Generating Prisma client..."
npx prisma generate

echo "Running database migrations..."
npx prisma migrate deploy || {
  echo "Migration failed, attempting to baseline the database"
  
  # Make migrations directory if it doesn't exist
  mkdir -p prisma/migrations/0_baseline
  
  # Create a baseline migration
  echo "-- This is an empty migration that serves as a baseline for an existing database
-- It was auto-generated by the entrypoint script" > prisma/migrations/0_baseline/migration.sql
  
  # Create migration metadata
  echo '{
  "version": "0.3.14-fixed",
  "description": "Baseline existing database",
  "dialect": "postgresql"
}' > prisma/migrations/0_baseline/migration.toml
  
  # Mark the baseline as applied
  npx prisma migrate resolve --applied 0_baseline
  
  # Try running migrations again
  echo "Rerunning migrations after baselining..."
  npx prisma migrate deploy
}

echo "Starting NestJS application..."
if [ -f "dist/main.js" ]; then
  node dist/main.js
elif [ -f "dist/src/main.js" ]; then
  echo "Found main.js in dist/src/ instead of dist/"
  node dist/src/main.js
else
  echo "ERROR: Application file not found in dist/main.js or dist/src/main.js!"
  echo "Directory contents of dist:"
  ls -la dist/
  echo "Directory contents of dist/src (if exists):"
  ls -la dist/src/ || echo "dist/src directory not found"
  exit 1
fi